finance_related_text = [
    "Cash",
    "Account Receivable",
    "Account Payable",
    "Revenue",
    "Capital Investment",
    "Salary Expense",
    "Total",
    "82.000",
    "25.000",
    "14.000",
    "100",
    "10",
    "1",
    "Debit",
    "Credit",
    "Expense",
    "Investment",
    "The total ammount of revenue",
    "Transaction in Transaction out",
    "Account name",
    "Bank/Cash Balance",
    "Money in",
    "Money out",
    "Income",
    "Bank",
    "Closing balance",
    "$,€,£",
    "Date: Jul, Jun",
    "Jun",
    "Jul"
]
#Nr. of words = 30

non_finance_related_text = [
    "Weather",
    "Vacation",
    "Book",
    "Movie",
    "Pets",
    "I'm planning a DIY home renovation project for the summer.",
    "My favorite pastime is attending live music concerts with friends.",
    "My favorite hobby is gardening in my backyard.",
    "I love animals",
    "happiness",
    "Garden",
    "Fashion",
    "Math is used quite a lot",
    "Jumping up and down on my trampoline",
    "Food",
    "Family gathering",
    "Freinds",
    "People",
    "The weather is cold today",
    "That is why people can't enjoy themselves",
    "I love the world",
    "Why do i have to that?",
    "Can humans fly?",
    "I would like to travel around the world",
    "I love buying clothes",
    "Can i ask you a question?",
    "Are you going to eat the sandwich?",
    "Oh yes i love the different cultues around the world",
    "This weekend i am going to visit my mother"
]
#Nr. of words = 29